// to fetch the api and make it display the screen


// let URL = "link of the api";
// const showapi = document.querySelector("#showapi");

// const clickandshow = document.querySelector("#clickandshow")

// cosnt getAPIdata = async () = > {

//    let response = await fetch(URL)

//    let data=  await Response.URL

//  showapi.innerText =  data.text

// } 

// clickandshow.addEventListener("click,getAPIdata")
